I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/Story/hubs.rpy", line 60, in script
    $ progess += 1
  File "game/scripts/Story/hubs.rpy", line 60, in <module>
    $ progess += 1
NameError: name 'progess' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/Story/hubs.rpy", line 60, in script
    $ progess += 1
  File "C:\Users\Rilogator\Documents\Game Dev\RenPy\renpy-7.3.2-sdk\renpy\ast.py", line 912, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Rilogator\Documents\Game Dev\RenPy\renpy-7.3.2-sdk\renpy\python.py", line 2004, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/scripts/Story/hubs.rpy", line 60, in <module>
    $ progess += 1
NameError: name 'progess' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.2.320
Gem Blast 3.0.0
Fri Nov 01 22:48:10 2019
